### PR TITLE
Updates module with latest ruby and terraform support. Provider updat…

### PR DESCRIPTION
**Pull request by broestls**
…es hampered by permissions questions that may or may not be resolved before launch date

### CODE REVIEW

**Review by mirestrepo — APPROVED** [review]
This is great.

There are few other updates that could be made to the GitHub actions. 

- Use the docker official actions to handle build and push as done in most other modules
- Update the action versions in the realse drafter and pr-labeler flows. 

Do you want to merge this and make new issues for those? Or do you want to push them here?

**Review by digicosmos86 — APPROVED** [review]

**Comment by digicosmos86** [comment]
Hi @broestls! Do you think we are ready to merge this?

**Comment by broestls** [comment]
@digicosmos86 Absolutely! LGTM.

**Comment by digicosmos86** [comment]
> @digicosmos86 Absolutely! LGTM.

Thanks @broestls!

**Pull request merged**
